### ISSUE TITLE
"Software" vs "Source Code"?

### ISSUE THREAD

**Issue by cboettig** [danielskatz/software-vs-data#1]
Are we including 'source code' in the definition of software?  I imagine the Ontology folks and pure CS folks think of these two terms as totally different beasts, while the domain scientist reading this probably doesn't distinguish so clearly and may assume (as I do) that this document covers source code.

I'm thinking of submitting an PR along the lines that Software exists both as source code and as platform-specific (i.e. hardware, operating system, etc) binaries (... or byte code, platform specific source code that may be generated programatically).  Also, how (executable) software differs from data isn't always the same as how source code differs from data; so this could have implications for the other sections (i.e. source code is often small, but a virtual machine with all dependencies isn't)

**Comment by npch** [comment]
Likewise, where do we place "models" e.g. those used in the biosciences, and those used in electrical engineering? They could be called software or source code, but are often classified as data in both communities, and potentially sit midway between them.

**Comment by danielskatz** [comment]
The question about source code vs software is a good one.

Also, I like the license distinction that @cboettig introduced in https://github.com/danielskatz/software-vs-data/commit/92fd72e9183eb69a1c8ff5687c27d361fbfc502a  Software is something that should have a software license, while data can use a creative commons license.  I'm not sure if this helps for models, however.

**Comment by danielskatz** [comment]
@cboettig, I think your PR for software existing as both source code and binaries (or services) would be useful.  Please go ahead with this if you can.

@npch, I'm not sure what to do about models.  What do you suggest?

**Comment by danielskatz** [comment]
@cboettig, @npch do you have any further thoughts/actions on this?  Or should we close the issue?
