### ISSUE TITLE
Software teams can be large and multidisciplinary, and with varied roles that overlap and sometimes make contributions ambiguous—some of which can rise to a level equivalent to paper authorship.

### ISSUE THREAD

**Issue by jennielarkin** [danielskatz/software-vs-data#10]
This one is (IMHO) very weak: data productions teams can (in some instances) also be large, complex, with varied roles.  And the lead in a data production effort should also be the equivalent to paper authorship.

**Comment by BergFulton** [comment]
I concur. In many instances, without data production, there is no software or paper to be written.

**Comment by jameshowison** [comment]
I think we're talking about a distribution here. My intuition is that both distributions (of counts of contributors) are heavily right-skewed (concentrations around 1) but that (widely used, publically available, updated) software is less so. But it is interesting that we really don't have data on that. Anyone know of studies that examine the number of contributors to datasets?

**Comment by knarrff** [comment]
If you look at datasets that come from LIGO or the LHC, the contributor list is at least in the thousands. I think that regarding numbers of 'contributors' data and software are more equal than different.

**Comment by jameshowison** [comment]
You may well be right :) I think what really matters is discussing how these issues affect citation. Large contributor lists are a challenge for any citation approach (data, software, papers) and changing contributor lists are an even greater challenge (and one that papers don't typically face). Perhaps it would make more sense to write about how change along many dimensions generates problems for citations (or for the credit giving/locating functions that we seek to achieve through citation)?

**Comment by knarrff** [comment]
One difference one might point out is indeed, while both might have a long contributors list, data usually is taken at a specific point in time, with that list then fixed. Citations would be made for these data, with these contributors. This is different for software, where contributors come and go and citations don't (at the moment) reflect that at all.

**Comment by danielskatz** [comment]
As I think about this, I'm unsure that there is a significant difference between data and software citation regarding this, and am tempted to remove this item.  Or maybe the title isn't quite right.

Suggestions for changes?

**Comment by knarrff** [comment]
The only item really is that the more authors some piece of work has, the more likely that list is to change, for software -  not so for data.

**Comment by danielskatz** [comment]
removed this point in https://github.com/danielskatz/software-vs-data/commit/37c63b161f7b7cc6f8cf8fe34957a64e6c601a68
