### ISSUE TITLE
The lifetime of software is generally not as long as that of data.

### ISSUE THREAD

**Issue by jennielarkin** [danielskatz/software-vs-data#11]
I would like quantitative proof of this one: this seems like someone’s assumption.  Some data is long-lived and ought to be sustained for a long time.  However, that is not necessarily the case for all data.  One can easily say the same thing for software.   I suspect there is a range for both data and software.

**Comment by danielskatz** [comment]
This is discussion that should be part of #6 - so closing this one for now...
