### ISSUE TITLE
Software is active, data is passive

### ISSUE THREAD

**Issue by tompollard** [danielskatz/software-vs-data#15]
This may just be another way of saying "Data provides evidence, software provides a tool", but I think a functional way of distinguishing between software and data is to say that software is active, while data is passive. 

By this I mean that software generally performs a function upon something (e.g. software processes data), while data generally has a function performed upon it (e.g. data is processed by software).

**Comment by danielskatz** [comment]
Feel free to add this as a pull request.

**Comment by band** [comment]
The difference is not about activity. It is, as @tompollard notes, that "data is processed by software". This is a key property and is separate from the others. I suggest changing "Software is active, data is passive." to either "Data is processed by software." or maybe "Software is run on hardware, data is processed by software."

**Comment by tompollard** [comment]
By active and passive, I'm just trying to draw the distinction between "acting upon something" (active, software) and "being acted upon" (passive, data)". 

There may be a clearer way of phrasing this, but I think that "data is processed by software" isn't quite right because it misses cases like "Data is generated by software".

**Comment by danielskatz** [comment]
we already have "software is executable, unlike papers or data" as the first difference.  Maybe we can change that to "software is executable, data is not" and drop this one?

**Comment by danielskatz** [comment]
resolved by https://github.com/danielskatz/software-vs-data/commit/3589769f115f7d16d4dc57230a5bc7bfaf22d1a8
