### ISSUE TITLE
Software can be used to express or explain concepts, unlike data.

### ISSUE THREAD

**Issue by BergFulton** [danielskatz/software-vs-data#18]
`Software can be used to express or explain concepts, unlike data.`
If we're believing that software consumes/transforms/acts upon data to yield evidence/understanding (am I reading the discussion correctly on that?)...can software do this without data? If we remove the last part of the sentence and leave it as `Software can be used to express or explain concepts.` then that reads as false to me? This might be the humanist in me coming out, but would software without data explain things to us?

From my work, I'd express this as `"Software can be used to express or explain concepts that raw aggregate data cannot. Software acts upon data to provide insight that is not possible without the computational and transformational abilities of software."`

For me, this looks like the fact that I've got 16,000+ art sale incidents in London from 1791-1913. Wayyyy too much for my human peabrain to process and make sense of, so I use software to get that data to tell me what's what. But if I didn't feed the software those 16,000 incidents, it'd just be an interface? 

I wonder if the converse of this statement is true.
`Data can be used to express or explain concepts.` It just may not be very easy without software.

**Comment by danielskatz** [comment]
One point that may be missing from the discussion is that there are different types of software.  Some software is data analysis & data transformation, which I think is what you are talking about, but there is also modeling and simulation software, which is quite different.

**Comment by BergFulton** [comment]
@danielskatz Yes, that would be a great clarification to make. But w/o that clarification or an understanding of what software is being discussed through the whole paper or defining terms somewhere, this sentence is a bit problematic?

**Comment by kyleniemeyer** [comment]
I definitely agree with @danielskatz that software does not require data to act upon—in fact a good portion of modeling/simulation software generates data from first principles or governing equations, and does not require data to start with (well, _some_ data, such as input parameters) to produce knowledge or understanding.

**Comment by ypriverol** [comment]
@danielskatz I agree with this idea `Software can be used to express or explain concepts, unlike data.` in lot of cases software is not only data transformation. It also create new knowledge, concepts and evidences. For example, inference algorithms in general (through software) can produce new data evidences that can't be explain without the software. 
Software can produce theoretical data that helps to understand concepts, ideas, etc. At the same time I think the sentence can be to strong if we only say that is only software which provides concepts, ideas, etc. What about: 
 `Software can be used to express or explain concepts, that sometimes raw aggregate data cannot. Software acts upon data to provide insight that is not possible without software abilities. It can helps to explain concepts theoretically beyond the experimental data`

**Comment by BergFulton** [comment]
@kyleniemeyer I agree, modeling/sim software is a great example of knowledge production sans data. I think that goes back to @danielskatz comment about needing to define software a bit to help the setup. 

@ypriverol's comment is well taken too. 

What about this:
`Software can be used to express or explain concepts, and this intuition [there's likely a better word but I've not got it at the moment] is not necessarily dependent upon data.`

**Comment by danielskatz** [comment]
I've merged this into the Software provides a tool items
