### ISSUE TITLE
Data provides evidence, software provides a tool.

### ISSUE THREAD

**Issue by ypriverol** [danielskatz/software-vs-data#19]
`Data provides evidence, software provides a tool`

The title for the section minimize the impact of the software. Taking the previous comments in issue #18 . Probably can be rephrase to: 

`Data provides evidence, software provides knowledge` 

Knowledge is more broadly scope including visualisation, data analysis, etc. I don't think software is only a tool.

**Comment by jayjaybillings** [comment]
I was just about to enter a ticket too. I think that the statement as written implies that software is not evidential, but in far too many cases it is. Source code for a given tool, for example, provides evidence that the tool is running as expected and can, in the case of many government codes, be the basis for validation and verification arguments. We might argue that in that case "the software becomes data in a review," but that seems to be splitting hairs.

**Comment by danielskatz** [comment]
How about
`Data provides factual evidence, software provides executable evidence and knowledge`

**Comment by ypriverol** [comment]
I like that, I can make the changes and in my pull-request if you are happy with that.?

**Comment by danielskatz** [comment]
let's see what others think for a day, then either you or I can change it.

**Comment by band** [comment]
At the risk of making more work that we want to put in I think that this distinction does not add value to the objective of providing measurable properties that can be used as citation information for software. The intro paragraph provides a concise and usable definition for "software" that many will agree with. "Knowledge" is a harder concept to define and get agreement on.

I think that this project is better served by avoiding comparisons  of software with datasets (and data). Defining and illustrating citation properties for software seems like a more grounded approach. One way to proceed with this is to review and refer to the 2013 report of the CODATA-ICSTI Task Group on Data Citation Standards and Practices: "OUT OF CITE, OUT OF MIND: THE CURRENT STATE OF PRACTICE, POLICY, AND TECHNOLOGY FOR THE CITATION OF DATA" (http://doi.org/10.2481/dsj.OSOM13-043). In particular, Chapter 2 of this report has a thorough, up to date, set of definitions of the concepts and characteristics of scientific and technical data.

I have not worked this up, but I think that using the ICSTI report as a start for scientific and technical data and dataset properties might be a way of describing software artifacts, or provide properties that can be adapted. In addition, the ICSTI report also has a thorough description of the issues and challenges of data citation, some of which, I imagine, will also apply to software.

Perhaps this comment needs to be fleshed out in the Introduction. I am willing to write that up (and provide a pull request). Please let me know (1) if this fits with your vision and (2) the best ways to proceed. I think defining software citation properties is important.

**Comment by danielskatz** [comment]
> I think that this project is better served by avoiding comparisons of software with datasets (and data). 

Unfortunately, that's the point of this project (or at least this repo) :)

On one hand, I am fully convinced that software is not the same as data, and believe that these differences lead to differences between how data should be cited and how software should be cited.  More specifically, while we can treat software as a kind of data, doing so would be lossy. By taking advantage of the characteristics of software, we can have better citation practices than if we simply cited software as if it was data.

On the other hand, any specific suggestions on citation of software that you have are very much welcome.

I'm sorry that I'm not really answering your 2 questions, but I don't have a simple answer.

**Comment by band** [comment]
I think you have answered both questions.

I am interested in the work here from a metrics-based perspective. What are the persistent and measurable properties of scientific and technical software that can be used to support citation?
I will look through the ICSTI data citation report and pull out the properties that are defined and used in citations and post them here somewhere (do you have a suggestion?) else on this repo.

Having better citation practices for S&T software is important and needed.

**Comment by danielskatz** [comment]
HI @band - Has there been any progress on what you suggested above?  Otherwise, I would like to close this issue

**Comment by band** [comment]
@danielskatz short answer "no". I have been consumed full-time for the past 7+ weeks with a family emergency. I will not be able to pick this up for a while. If I pull something  together later we can figure out if it is useful then.
