### ISSUE TITLE
preprint.bib abstract suggestion 1

### ISSUE THREAD

**Issue by band** [danielskatz/software-vs-data#36]
Make this sentence part "the goal of the working group was to produce a consolidated set of citation principles that may encourage broad adoption of a consistent policy for software citation" stronger by replacing "that may encourage" with "to encourage".
Rationale: stronger statement, and we do want to encourage change.

**Comment by danielskatz** [comment]
thanks - will do

**Comment by danielskatz** [comment]
sorry, where is this text?  Can you suggest this change as a PR?

**Comment by danielskatz** [comment]
proposed in #37 but not possible to change
