### ISSUE TITLE
suggestions for edits

### ISSUE THREAD

**Issue by bboscoe** [danielskatz/software-vs-data#39]
Hi all, sorry I am a bit late to the party. If it is not too late, my suggestions are as follows:
1. Glad to find better refs than wikipedia references (especially in light of the large funding blasts on each Wikipedia page).

2.There's no mention of definitions of software vs. code. Seems like a distinction worth noting- I can write a bit on that too.

3. Are patents important to mention alongside the copyright issues?

4. From this paper, and I agree, software is more fragile than data-- perhaps a bit more elaboration on this due to its fluid-like state? On that-- thoughts on distinctions between scripts and compiled code (wrt citations of course)

--Bernie

**Comment by rowlandm** [comment]
Can I second #2 please? Software is such a general term.

I work on big, complex multi-service web based software. Most of the time the "software" being talked about are command line or even desktop GUI environments. Yet more and more, web based portals are being used to share the data.

For example, no-one can use my software to run a server until they setup the environment across multiple servers. Should the person who does the DevOps be catered for in the citation? Should the Enterprise Architect that designed the system be included too? What about the person who helps maintain patches? I think the answer is yes - but I'm not 100% sure.

I don't know exactly the context of this document in terms of research citations but I thought I would add my comments nevertheless.

**Comment by danielskatz** [comment]
the easier ones first...

A PR for 1 would be very welcome.

What would you say for 3?

**Comment by danielskatz** [comment]
@rowlandm - This context for this document is https://doi.org/10.7717/peerj-cs.86

The model we discuss there is that the software is published to a repository, and the person who publishes it does so with metadata that includes all the people who should receive credit for it.  This publication process returns an identifier, which is what the software then asks users to cite.

**Comment by danielskatz** [comment]
@brandles 

re software vs code, I don't know that the distinction helps when the purpose is to differentiate software/code vs data.  Why do you think it does?

re software is more fragile than data, if you think there's more to say, please try a PR and lets see what others think.

**Comment by bboscoe** [comment]
What I am saying is the paper should define what software is. Software
could encompass code/scripts/compiled code/proprietary software.

**Comment by danielskatz** [comment]
ah, I see - can you add some text about this?

For example, in https://doi.org/10.7717/peerj-cs.86, we state "The principles and discussion in this document have generally been written to focus on software as source code. However, we recognize that some software is only available as an executable, a container, or a virtual machine image, while other software may be available as a service. We believe the principles apply to all of these forms of software, though the implementation of them will certainly differ based on software type."

**Comment by bboscoe** [comment]
Yes, that is along the lines of what I was thinking.I'll write up a
software paragraph.

 I tried to change the .bib file, swapping out the one wikipedia
homoiconicity reference, and got an authentication error. Here's what I was
trying to put in:

@phdthesis{Kay:1969:RE:905541,
 author = {Kay, Alan Curtis},
 title = {The Reactive Engine},
 year = {1969},
 note = {AAI7003806},
 publisher = {The University of Utah},
}

I figure the Kay reference is as good as any.

**Comment by danielskatz** [comment]
> Yes, that is along the lines of what I was thinking.I'll write up a software paragraph.

thanks.

> I tried to change the .bib file, swapping out the one wikipedia homoiconicity reference, and got an authentication error. Here's what I was trying to put in:

to make changes, you need to submit a pull request, and ideally, you will change both the .tex/.bib and the .md so that they continue to match

**Comment by danielskatz** [comment]
@brandles can this issue be closed? Or is there still something here to be done?

**Comment by bboscoe** [comment]
You can close it. I wanted to find some better data rot work, I'll keep
digging, haven't found anything I like.
