### ISSUE TITLE
Are we talking about function or form?

### ISSUE THREAD

**Issue by npch** [danielskatz/software-vs-data#4]
(aka the tomato paradox)

It strikes me that there are two sets of arguments about how we split software from data.

One set revolve around the use of software (e.g. the more fragile dependencies that cause increased bit rot, the way it tends to be reused). Another revolve around the form of software (e.g. software code as an interpretation of an algorithm, rather than a statement).

This seems similar to the argument surrounding the tomato - in form it is a fruit, in function it is a vegetable.

**Comment by danielskatz** [comment]
I agree with what you are saying.  Perhaps there are also other arguments, such as @cboettig's creative work vs fact, which seems to overlap your form argument while also being somewhat distinct.

It would be nice to have a small set of orthogonal distinctions, though I am not sure if this is possible.  Maybe it is something to work towards as we build up the overall set.

**Comment by danielskatz** [comment]
resolved by https://github.com/danielskatz/software-vs-data/commit/c43d7abf874be4045f90619b99af07f235cbb6cc (or close enough to close this)
