### ISSUE TITLE
Granularity

### ISSUE THREAD

**Issue by zuphilip** [danielskatz/software-vs-data#40]
I would suggest to add another difference about the "granularity". For example if you think about nation-wide survey data, then they will give you a lot of different categories in each year, which itself will be spread over a lot of tables. Data providers can publish each year a) the new data once, b) the new data among different collections, c) a new data dump of everything (past+present).

On the other hand it might be that I want to cite i) the data as whole, or ii) just some specific table of the data, or iii) just one value from some data.

I don't think the same "granularity" exists in software citations, also there might be different versions...

Let me know what you think about this one. I can search for some examples and references.

**Comment by danielskatz** [comment]
I think that this granularity does have a parallel in software.  A code repository might also have text documents or even sample data inside.

In some sense, a data collection is different than just data, and a software repository is different than just source code.  Both are containers that include multiple types of objects.

**Comment by zuphilip** [comment]
Hm... okay, I see. One could say that both data and software can have some hierarchical structure of smaller parts, which could mean for software included libraries, folders or even separate files. I guess that this is then not a difference bot something they can have both.

For completeness:
 * Here is an example for research data: The doi [10.1787/govxp-table-2013-5-en](http://www.oecd-ilibrary.org/economics/government-final-consumption-expenditure-in-us-dollars-2013-5_govxp-table-2013-5-en) refers to a table from the "Economics: Key tables from the OECD" [10.1787/2074384x](http://www.oecd-ilibrary.org/economics/economics-key-tables-from-oecd_2074384x;jsessionid=co2ksqdb9q4qq.x-oecd-live-03) in the year 2013 in English.
 * The paper I had in mind is: [Supporting Data Citation: Experiences and Best Practices of a 
DOI Allocation Agency for Social Sciences](http://jlsc-pub.org/articles/abstract/10.7710/2162-3309.1220/)

**Comment by danielskatz** [comment]
As something that they can both have, it's interesting but not quite appropriate for this document, so I will close this issue, but thanks for bringing it up
