### ISSUE TITLE
Data Citation Principles

### ISSUE THREAD

**Issue by zuphilip** [danielskatz/software-vs-data#41]
I suggest a new reference (should IMO be easy to include it somewhere):

Data Citation Synthesis Group: Joint Declaration of Data Citation Principles. Martone M. (ed.) San Diego CA: FORCE11; 2014. https://www.force11.org/datacitation

**Comment by danielskatz** [comment]
Which difference does this citation support?

**Comment by zuphilip** [comment]
I would have imagined more to include it in the introduction.

Is there no connection to this FORCE11 initiative in 2016 about software citations to the FORCE11 initiative in 2014 about data citations?

**Comment by danielskatz** [comment]
Ok, can you create a pull request that adds this?  And also changes the README.md file to match?
