### ISSUE TITLE
"Software is updated more frequently than papers or data."

### ISSUE THREAD

**Issue by jennielarkin** [danielskatz/software-vs-data#8]
"Software is updated more frequently than papers or data.  Datasets can of course be frequently updated, but each update likely represents the findings of a new or repeated study."

I do not find the stated difference compelling.  This needs to be spelled out more, as there are  studies that produce complex, sometimes continuous data measurements.    I fail to see how a new software version is qualitatively different.  However, I assume there is some difference that needs to be better explained.

**Comment by danielskatz** [comment]
Ok - maybe this one should be dropped.

Are there any other people who see value in this and can explain why we should keep it?

**Comment by Melissa37** [comment]
Maybe the statement could be changed somewhat to reflect that the version of software referenced is a critical element of the citation but there is more flexibility and lower requirement to cite specific versions of data?

**Comment by danielskatz** [comment]
I will delete this one.
