### ISSUE TITLE
"Software is frequently built to use other software, leading to complex dependencies, and these dependent software packages also frequently change."

### ISSUE THREAD

**Issue by jennielarkin** [danielskatz/software-vs-data#9]
This document builds it up as an either— or, and it is  helpful to highlight areas where they are different. Yet I do not find this one convincing.  

Data can be very complex and go through multiple stages of processing.  In addition, such data and are thus inextricably bound with the software and workflows that produce them (and different versions as it gets processed).

**Comment by jameshowison** [comment]
I agree that there is a continuum here. However, I think that bit rot driven by change in the surrounding software ecosystem is much more pervasive and faster than with data. At least I think we have clearer evidence of that with software. I'd be really interested in ethnographies or other close studies of the work needed to re-use/maintain datasets. I'll ask around for some relevant citations.

**Comment by Melissa37** [comment]
Please don't loose this type of valuable information for novices to the software citation world and maybe place it elsewhere rather than delete it. It might not be significant enough a difference to data citations, but for people trying to source authorship of software citations when starting out this is very good information to hang on to. Thanks!

**Comment by danielskatz** [comment]
perhaps this should be merged with #12 and the two statements should also be merged.

**Comment by khinsen** [comment]
I agree with @jameshowison: there is no fundamental difference between software and data in this respect, but in practice, dependency graphs for scientific dataset are much smaller than for software.

But what is the point of mentioning this in the context of citation? There is the obvious problem of how much of the dependency graph should be cited, but are there actually any guidelines for this?

**Comment by danielskatz** [comment]
addressed by https://github.com/danielskatz/software-vs-data/commit/c62aed523ccc368d7508d7ea4de012ec2842c0d3
